# Exported from Render on 2026-09-15T20:26:39Z
version: "1"
projects:
- name: costos_backend
  environments:
  - name: Production
    services:
    - type: web
      name: costos_Backend
      runtime: docker
      repo: https://github.com/FritoMix/costos_Backend
      plan: free
      envVars:
      - key: url
        sync: false
      - key: user
        sync: false
      - key: database
        sync: false
      - key: port
        sync: false
      - key: host
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
